### PR TITLE
Add Language API to generated output

### PR DESCRIPTION
**Pull request by blowmage**
[refs #253]

### CODE REVIEW

**Comment by blowmage** [comment]
The samples are standalone, and not the inline samples. We could duplicate them to this repo and change them to be inline.

**Comment by quartzmo** [comment]
> The samples are standalone, and not the inline samples. We could duplicate them to this repo and change them to be inline.

Personally I'd like to see where we're at with inline samples, even if it means manually changing the configs that are currently available.

**Comment by blowmage** [comment]
I agree about changing the samples and supporting the inline sample type. But we have other samples that also need to be changed. Can we move this to a separate PR?

**Comment by dazuma** [comment]
Thanks Mike!

**Pull request merged**
