### PR TITLE
Remove frozen string magic comment

### PR DESCRIPTION
**Pull request by blowmage**

### CODE REVIEW

**Comment by blowmage** [comment]
Ruby 3.0 will no longer freeze all strings by default, so we are backing away from this. These magic comments are not required by the Google Ruby style.

**Comment by blowmage** [comment]
@dazuma Thoughts?

**Comment by dazuma** [comment]
I still like freezing strings by default. Just seems like good practice. (Assuming we ignore backward compatibility.)

**Comment by blowmage** [comment]
K, closing.

**Pull request closed without merging**
