### PR TITLE
fix: Disable BlockLength check for all sample tests, including in subdirectories

### PR DESCRIPTION
**Pull request by dazuma**
This affects google-cloud-vision, which has some samples in a `samples/product_search` subdirectory (and thus has tests in `samples/product_search/acceptance`)

### CODE REVIEW

**Comment by quartzmo** [comment]
Are you sure you want to exclude these files from rubocop? My understanding is that `spec` directory files in ruby-docs-samples are/were tested by rubocop, and I've maintained that compliance for all the specs that I've migrated to minitest (even in BigQuery [samples](https://github.com/googleapis/google-cloud-ruby/tree/master/google-cloud-bigquery/samples/snippets/acceptance)). Personally I would rather go the other direction, and try to improve the code style of tests in the veneers, although this is not high priority.

**Comment by viacheslav-rostovtsev** [comment]
I also am not sure why exactly the sub-folder tests should be excluded?

**Comment by dazuma** [comment]
@quartzmo @viacheslav-rostovtsev Sorry this wasn't clear: I'm disabling only the `Metrics/BlockLength` check. Tests with spec-style `describe` blocks cannot have this check enabled because a `describe` block can have an arbitrary number of examples and thus an arbitrary length. Agreed we should keep Rubocop as a whole enabled if possible, but a few specific checks cannot apply to tests.

**Comment by quartzmo** [comment]
Ugh, sorry, I didn't look closely enough at where the exclude was being applied.

**Pull request merged**
