### PR TITLE
fix: Fix out of date SDK auth documentation

### PR DESCRIPTION
**Pull request by SandeepTuniki**
This PR addresses the issue raised at: https://github.com/googleapis/google-cloud-ruby/issues/18901

It updates the generator template to indicate the correct command regarding authentication via Cloud SDK credentials.

Originally raised the PR (incorrectly) at https://github.com/googleapis/google-cloud-ruby/pull/19017

### CODE REVIEW

**Review by viacheslav-rostovtsev — APPROVED** [review]
LGTM

**Review by dazuma — APPROVED** [review]
LGTM.

Please use `fix:` for this change.

From the perspective of client libraries (i.e. in a pull request for google-cloud-ruby which releases client libraries), this is a `docs:` change, because the semantic effect on a client library is a correction to the documentation. But from the perspective of the generator (i.e. in a pull request in this repo which releases the generator), it is a `fix:` because it corrects a bug in the generator and should trigger a patch release for the generator.

**Comment by dazuma** [comment]
Oh, in addition, it looks like we need to regenerate the outputs used for the tests. You can do that by running, using Ruby 2.6:

```
bundle update
bundle exec rake bundle_update
bundle exec rake gen
```

**Comment by dazuma** [comment]
Then you can double-check that CI passes locally, by running

```
bundle exec rake ci
```

**Comment by SandeepTuniki** [comment]
Thanks @dazuma. I generated the outputs again. Now the tests are passing.

Also, the bundle update changed some of the gem versions in the Gemfile.lock files. Is that ok?

**Comment by dazuma** [comment]
> Also, the bundle update changed some of the gem versions in the Gemfile.lock files. Is that ok?

Totally fine. Thanks!

**Pull request merged**
