### PR TITLE
feat(common): Support for protobuf 4.x

### LINKED ISSUE #1080: Update google-protobuf dependency to >= 3.18 in gapic-common (add support for 4.x)
The `gapic-common` v0.21.1 depends on `google-protobuf ~> 3.18` (2021 vintage). This approximately equal dependency prohibits major version jumps and parent projects aren't able to add dependencies using the 4.x series of `google-protobuf` (v4.27.1 is the latest). 

Can we update the dependency to:
```
spec.add_dependency 'google-protobuf', '>= 3.18', '< 5.0'
```

Further context, `google-cloud-ai_platform-v1` depends on `gapic-common` causing this implicit legacy gem dependency

### PR DESCRIPTION
**Pull request by dazuma**
fixes #1080 

Dependent on the grpc 1.65.0 final release. Will remain in draft mode for testing until then.

### CODE REVIEW

**Comment by colinbendell** [comment]
[grpc 1.65](https://github.com/grpc/grpc/releases/tag/v1.65.0) was released June 28. How can I help move this out of draft?

**Comment by dazuma** [comment]
@colinbendell grpc 1.65.0.pre2 was released June 25 (https://rubygems.org/gems/grpc/versions) but I don't see a final 1.65.0 rubygem. I'll confirm with the grpc team.

**Comment by colinbendell** [comment]
> @colinbendell grpc 1.65.0.pre2 was released June 25 (https://rubygems.org/gems/grpc/versions) but I don't see a final 1.65.0 rubygem. I'll confirm with the grpc team.

Ah. Seems like your nudge helped. 1.65.0 was bumped to rubygems yesterday.

**Comment by dazuma** [comment]
> Ah. Seems like your nudge helped. 1.65.0 was bumped to rubygems yesterday.

Great! I'll do a final test and push through the rest of the stack in the next few days.

**Review by aandreassa — APPROVED** [review]

**Comment by dazuma** [comment]
@colinbendell FYI gapic-common 0.22.0 was released a few hours ago. Along with grpc >= 1.65.0 it should provide support for protobuf 4.x.

**Pull request merged**
