### PR TITLE
chore: add library_type to repo-metadata.erb template

### PR DESCRIPTION
**Pull request by trambui09**
For the GAPIC generator, in the repo-metadata.erb, add an additional library_type field and set it to be GAPIC_AUTO.

This is part of the internal issue #184315365.

### CODE REVIEW

**Review by dazuma — APPROVED** [review]
This looks good. We can probably use `feat:` as the conventional commit prefix, because this actually adds a feature and changes the behavior of the generators.

**Comment by dazuma** [comment]
It looks like the tests are still failing, because the built-in examples don't match the changes we've made. You'll need to regenerate the examples.

* Pull the latest branch. (Some changes have gone into the master branch in the meantime, and I've already merged them into your branch, so you'll need to pull the branch down to your laptop.)
* Run `bundle exec rake gen`. This will regenerate the examples.
* Then commit and push the change.

**Comment by trambui09** [comment]
> It looks like the tests are still failing, because the built-in examples don't match the changes we've made. You'll need to regenerate the examples.
> 
> * Pull the latest branch. (Some changes have gone into the master branch in the meantime, and I've already merged them into your branch, so you'll need to pull the branch down to your laptop.)
> * Run `bundle exec rake gen`. This will regenerate the examples.
> * Then commit and push the change.

I did this, I'm not sure if what I did was correct as it deleted more files rather than modified the files/regenerate the examples?

**Comment by dazuma** [comment]
Oh. Try this:

```
git submodule init
git submodule update
bundle exec rake bin
bundle exec rake gen
```

**Comment by trambui09** [comment]
Thanks Daniel! Just pushed up the updated regenerated examples!

**Review by viacheslav-rostovtsev — APPROVED** [review]

**Comment by dazuma** [comment]
Tests pass!

**Pull request merged**
