### PR TITLE
Refactor paths helper names

### PR DESCRIPTION
**Pull request by blowmage**
Some renames to make things more consistent.

### CODE REVIEW

**Comment by quartzmo** [comment]
This PR changes the name of the client from:

```rb
          client = Google::Cloud::Speech::V1::Speech.new
```
to
```rb
          client = Google::Cloud::Speech::V1::Speech::Client.new
```

I remember discussing this before, but what is the motivation again?

**Comment by quartzmo** [comment]
Also, why the change from `client` to `service` in the templates?

**Comment by blowmage** [comment]
The client name is only changed in the tests. The rest of the generated output remains the same. I left this change in the test output because the error message makes more sense with it. For example, the method `Google::Showcase::V1alpha3::Echo#echo` does not exist, but `Google::Showcase::V1alpha3::Echo::Client#echo` does. But we can change the generated output back by using the correct helper method.

**Comment by blowmage** [comment]
> Also, why the change from client to service in the templates?

The template files and their names pre-date the introduction of the presenters. If you look at how these files are used in the generator, they are all used by the same presenter. So I felt it was better to organize them by how they are used in the generator.

`client` is still a concept within `service`, just as is `credentials` and `paths` and `test`.

**Comment by blowmage** [comment]
> I'm not sure what makes Google::Showcase::V1alpha3::Echo a _service_

That is the module that the other protoc plugin creates that contains the `Service` class and the `Stub` constant. We re-use the same module and create `Class` and `Credentials` classes, as well as a `Path` module. We also add a `.new` method to the service module.

**Comment by dazuma** [comment]
Does make me wonder if the alias should be `Google::Showcase::V1alpha3::Echo.client` instead of `Google::Showcase::V1alpha3::Echo.new`

**Comment by quartzmo** [comment]
@dazuma Personally I prefer factory methods to be explicit, and I consider implementing `.new` to be a bit of misleading trickery. I would prefer `Google::Showcase::V1alpha3::Echo.client`.

**Comment by blowmage** [comment]
Yeah, we have had discussions about this before. The current generator adds a `.new` method to both the service module, and the gem module (`Google::Showcase.new`). I think the service constructor is helpful, but I don't think the gem constructor is helpful, especially because you never know what service is going to be created, and you kinda need to know that to know how to construct proper messages.

If we renamed the service constructor method from `Echo.new` to `Echo.client`, we would have a natural place to add an `Operations` client at `Echo.operations`. At that point, why not also add `Echo.credentials` to create a `Credentials` instance?

**Comment by blowmage** [comment]
What do you think about nesting all the gem templates in a gem directory?

**Comment by blowmage** [comment]
Updated. PTAL.

**Comment by blowmage** [comment]
Let's move the service constructor method discussion to #124.

**Pull request merged**
