### PR TITLE
Separate Docker images for base generator and subgenerators

### PR DESCRIPTION
**Pull request by dazuma**
This PR moves the toplevel Dockerfile and entrypoint into the base generator directory (because it is an entrypoint specifically for the base generator) and creates another Dockerfile and entrypoint for the cloud subgenerator (which can be used as a template for further subgenerators). It has been carefully written so that it will still function if/when a subgenerator is broken out into a separate repo.

Specifics:
* The existing toplevel `docker-entrypoint.sh` and `Dockerfile` were moved under the `gapic-generator` directory.
* Altered the gemspecs so that they no longer invoke `git` to determine which files to use. This is because we are now docker building from inside a subdirectory, and the `.git` directory is no longer available, so we can't invoke git.
* I altered the directory structure of the docker image a bit. Stuff is no longer installed or mounted in the root directory. Instead, everything specific to the generator is located under `/workspace`. Specifically:
    * The input directory moved from `/in` to `/workspace/in`.
    * The output directory moved from `/out` to `/workspace/out`.
    * The config file moved from `/config.yaml` to `/workspace/config.yaml`.
    * The common protos moved from `/protos` to `/workspace/common-protos`.
    * The entrypoint script and `gapic.sh` have been altered to use these updated paths.
* I reworked the Dockerfile to be two-stage, in order to reduce confusion in the final runtime image. (For example, previously, the final runtime image had the source located under `/usr/src/gapic-generator-ruby` but this was not actually used at runtime because the gem was installed.) Now, the first stage copies the source directory and builds `*.gem` files, and the second stage just installs the gems.
* I determined that the file permissions culprit is the `google-style` gem. I'm working on fixing it (https://github.com/googleapis/ruby-style/pull/16), and I've separated out the file permissions hack so we can remove it once the fixed.
* Added rake tasks for building the images.
* The cloud subgenerator versions of the Dockerfile and entrypoint script are slightly different from the base generator versions in that they have the option of building the base generator from source. (Normally they would just install the base generator gem from rubygems, which is what we expect once we break the subgenerator into a separate repo.) Specifically, if you copy the base generator source directory into `tmp/` within the subgenerator source tree when building the docker image, it will use that to build the base generator from source. (Note that we must make a copy of the base generator source; the base generator directory is not otherwise accessible from inside the subgenerator directory during a docker build.) There is a special rake task that performs this kind of build for the cloud subgenerator.
* Updated the gem_templates to include the above changes when creating a new subgenerator.

### CODE REVIEW

**Comment by dazuma** [comment]
Answers to above questions:

1. I experimented with `slim`, and it is possible to use it, but we'd have to install a bunch of additional packages (notably development tools so that gems like nokogiri can build). Staying with `stretch` means we don't need that extra complexity in the dockerfile. I judged the difference in image weight wasn't enough to offset the complexity.
2. Yes, you're right, any subgenerator will need the `gapic.sh` script. But the way it is currently set up, the text of `gapic.sh` will likely be identical regardless of which generator is being used. (You pass an `--image` argument `gapic.sh` to select the generator image; otherwise the usage and behavior is identical.) So yeah, when we move the ads generator out into a separate repo, we'll copy `gapic.sh` into that repo. But for now, I'm thinking of keeping a single copy of the file.

**Comment by dazuma** [comment]
Oh, but you're right: we should include `gapic.sh` in the gem generation templates. I'll add that...

**Comment by quartzmo** [comment]
1. SGTM, let's stick with `stretch`.
2. I'll pull the branch, temporarily move `gapic.sh` to a subgenerator directory, and confirm that it works ok.

**Comment by blowmage** [comment]
Looks like the expected output doesn't match what is being generated. Can you run `bundle exec rake gen` from the root directory to update it?

**Comment by dazuma** [comment]
Tests are finally fixed!

**Comment by quartzmo** [comment]
I built the `gapic-generator` Docker image and ran it locally with Ads protos as follows:

```
$ sh gapic.sh --image gapic-generator -p /Users/quartzmo/code/google/codez/gapic-generator-ruby/shared/googleapis -i google/ads/googleads/v1 -o ../../gapic-generator/test-out-1 --config ../config/googleads.yml
```

It worked fine, and as you said `gapic.sh` in its current form will work correctly from any location, as long as you get the relative paths right.

**Pull request merged**
