### PR TITLE
fix: Set Credentials defaults using constants not superclass methods

### PR DESCRIPTION
**Pull request by quartzmo**
closes: #534
refs: googleapis/google-cloud-ruby#8610

### CODE REVIEW

**Comment by viacheslav-rostovtsev** [comment]
Could it be that someone depends on the new behaviour and we need to **add** constants, instead of **replacing** class-instance variables with them?

**Comment by quartzmo** [comment]
> Could it be that someone depends on the new behaviour and we need to add constants, instead of replacing class-instance variables with them?

From static inspection of the code, I don't see how this is possible. But please take a look for yourself at the [usages of `@scope` in `Credentials`](https://github.com/googleapis/google-auth-library-ruby/blob/master/lib/googleauth/credentials.rb#L97-L127):

Currently, the setter `scope=` sets the instance variable `@scope`. The visibility of this variable is **limited to the Credentials class (or subclass)** upon which the setter is called. There is no inheritance of this instance variable since it is **not** a **class variable** and is used in a class method and not an instance method. (Confusing, I know! "Classes in Ruby are first-class objects—each is an instance of class Class" [see Class docs](https://ruby-doc.org/core-2.7.2/Class.html).)

The user can only read the value using the getter `scope`. This will read the value if is found on the instance variable, but failing that, it will read it from the constant if available.

```
      def self.scope
        return @scope unless @scope.nil?

        Array(const_get(:SCOPE)).flatten.uniq if const_defined? :SCOPE
      end
```

I really can't imagine how someone depends on the instance variables being set in a way that wouldn't be handled by these getters, but maybe I just lack imagination.

**Comment by viacheslav-rostovtsev** [comment]
Yes, that makes sense.

**Review by viacheslav-rostovtsev — APPROVED** [review]

**Comment by dazuma** [comment]
Ah, shoot. We had intentionally changed from constants to class methods here, for reasons. I really don't want to go back if we can help it. Can we hold off just for a bit while I investigate if there's a way to fix this in the googleauth base class instead?

**Comment by dazuma** [comment]
I suggest we do this instead: https://github.com/googleapis/google-auth-library-ruby/pull/284

**Comment by quartzmo** [comment]
Closing in favor of googleapis/google-auth-library-ruby#284. Bravo!

**Pull request closed without merging**
