### PR TITLE
Add check_protos rake task

### PR DESCRIPTION
**Pull request by blowmage**
Ensures that the protos are compiled before using.

### CODE REVIEW

**Comment by quartzmo** [comment]
I pulled this branch and ran:

```sh
$ bundle update
$ bundle exec rake update
$ bundle exec rake ci
bundle exec rake check_protos
checking for protoc-gen-ruby... yes
grpc_tools_ruby_protoc --plugin=protoc-gen-ruby-protobuf=/Users/quartzmo/.rbenv/versions/2.5.3/gemsets/gapic-generator-ruby/bin/protoc-gen-ruby --ruby-protobuf_out=lib -I ../shared/api-common-protos -I ../shared/protobuf/src ../shared/api-common-protos/google/api/annotations.proto ../shared/api-common-protos/google/api/client.proto ../shared/api-common-protos/google/api/field_behavior.proto ../shared/api-common-protos/google/api/resource.proto ../shared/api-common-protos/google/longrunning/operations.proto ../shared/protobuf/src/google/protobuf/descriptor.proto ../shared/protobuf/src/google/protobuf/compiler/plugin.proto
../shared/protobuf/src: warning: directory does not exist.
../shared/api-common-protos/google/api/annotations.proto: No such file or directory

Running CI for shared
bundle exec rake ci
bundle exec rake check_protos
checking for protoc-gen-ruby... yes
grpc_tools_ruby_protoc --plugin=protoc-gen-ruby-protobuf=/Users/quartzmo/.rbenv/versions/2.5.3/gemsets/gapic-generator-ruby/bin/protoc-gen-ruby --ruby-protobuf_out=lib -I ../shared/api-common-protos -I ../shared/protobuf/src ../shared/api-common-protos/google/api/annotations.proto ../shared/api-common-protos/google/api/client.proto ../shared/api-common-protos/google/api/field_behavior.proto ../shared/api-common-protos/google/api/resource.proto ../shared/api-common-protos/google/longrunning/operations.proto ../shared/protobuf/src/google/protobuf/descriptor.proto ../shared/protobuf/src/google/protobuf/compiler/plugin.proto
../shared/protobuf/src: warning: directory does not exist.
../shared/api-common-protos/google/api/annotations.proto: No such file or directory


shared test
Running CI for gapic-generator
bundle exec rake ci
checking for protoc-gen-ruby... yes
grpc_tools_ruby_protoc --plugin=protoc-gen-ruby-protobuf=/Users/quartzmo/.rbenv/versions/2.5.3/gemsets/gapic-generator-ruby/bin/protoc-gen-ruby --ruby-protobuf_out=lib -I ../shared/api-common-protos -I ../shared/protobuf/src ../shared/api-common-protos/google/api/annotations.proto ../shared/api-common-protos/google/api/client.proto ../shared/api-common-protos/google/api/field_behavior.proto ../shared/api-common-protos/google/api/resource.proto ../shared/api-common-protos/google/longrunning/operations.proto ../shared/protobuf/src/google/protobuf/descriptor.proto ../shared/protobuf/src/google/protobuf/compiler/plugin.proto
../shared/protobuf/src: warning: directory does not exist.
../shared/api-common-protos/google/api/annotations.proto: No such file or directory


BUILDING gapic-generator

gapic-generator rubocop
Running RuboCop...
Inspecting 21 files
.....................

21 files inspected, no offenses detected

gapic-generator test
Traceback (most recent call last):
	11: from /Users/quartzmo/.rbenv/versions/2.5.3/gemsets/gapic-generator-ruby/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:4:in `<main>'
	10: from /Users/quartzmo/.rbenv/versions/2.5.3/gemsets/gapic-generator-ruby/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:4:in `select'
	 9: from /Users/quartzmo/.rbenv/versions/2.5.3/gemsets/gapic-generator-ruby/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:15:in `block in <main>'
	 8: from /Users/quartzmo/.rbenv/versions/2.5.3/gemsets/gapic-generator-ruby/gems/rake-10.5.0/lib/rake/rake_test_loader.rb:15:in `require'
	 7: from /Users/quartzmo/code/google/codez/gapic-generator-ruby/gapic-generator/test/gem/gem_builder_test.rb:17:in `<top (required)>'
	 6: from /Users/quartzmo/code/google/codez/gapic-generator-ruby/gapic-generator/test/gem/gem_builder_test.rb:17:in `require'
	 5: from /Users/quartzmo/code/google/codez/gapic-generator-ruby/gapic-generator/test/test_helper.rb:18:in `<top (required)>'
	 4: from /Users/quartzmo/code/google/codez/gapic-generator-ruby/gapic-generator/test/test_helper.rb:18:in `require'
	 3: from /Users/quartzmo/code/google/codez/gapic-generator-ruby/gapic-generator/lib/google/gapic/schema/api.rb:17:in `<top (required)>'
	 2: from /Users/quartzmo/code/google/codez/gapic-generator-ruby/gapic-generator/lib/google/gapic/schema/api.rb:17:in `require'
	 1: from /Users/quartzmo/code/google/codez/gapic-generator-ruby/gapic-generator/lib/google/gapic/schema/loader.rb:17:in `<top (required)>'
/Users/quartzmo/code/google/codez/gapic-generator-ruby/gapic-generator/lib/google/gapic/schema/loader.rb:17:in `require': cannot load such file -- google/api/annotations.pb (LoadError)
```

**Comment by quartzmo** [comment]
Sorry, I just needed the submodules, thanks for the help.

**Comment by quartzmo** [comment]
Actually, I mean do you want to raise if the files are not present?

**Comment by blowmage** [comment]
I dunno. At first glance I feel like the rake tasks are in charge of generating the files, but they aren't in charge of keeping the submodules up to date. Like that is outside of their area of their domain of responsibility. What do you think?

**Comment by quartzmo** [comment]
SGTM, I'll merge now.

**Pull request merged**
